defaults:
    - override hydra/launcher: submitit_local

# task
task: cheetah-run
steps: 10000000
obs_mode: state

# planning
mpc: true
iterations: 6
num_samples: 512
num_elites: 64
num_pi_trajs: 24
min_std: 0.05
max_std: 2
temperature: 0.5

# actor
log_std_min: -10
log_std_max: 2
entropy_coef: 1e-4

# critic
num_bins: 101
vmin: -10
vmax: +10

# learning
batch_size: 256
horizon: 3
reward_coef: 0.1
value_coef: 0.1
consistency_coef: 20
rho: 0.5
lr: 3e-4
enc_lr_scale: 0.3
max_norm: 20
tau: 0.01
utd_ratio: 1
buffer_size: 1000000

# architecture
arch: manual
num_enc_layers: 2
enc_dim: 256
mlp_dim: 512
latent_dim: 512
task_dim: 96
num_q: 5
dropout: 0.01
simnorm_dim: 8
simnorm_tau: 1

# pretrain
pretrain: false
multitask: false
task_set: dmc19

# wandb
wandb_project: tdmpcv2
wandb_entity: nicklashansen

# dirs
logging_dir: .
buffer_dir: /data2/nihansen/code/tdmpcv2/buffer

# misc
seed: 1
exp_name: dev
eval_freq: 50000
eval_episodes: 10
save_video: true
save_buffer: false
save_agent: true
visualize_plan: false
disable_render: false

# convenience
work_dir: ???
task_title: ???
device: ???
obs_shape: ???
action_dim: ???
obs_shapes: ???
action_dims: ???
episode_length: ???
seed_steps: ???
bin_size: ???
aux_dim: ???
