apiVersion: batch/v1
kind: Job
metadata:
  name: {{name}}
spec:
  template:
    spec:
      containers:
      - name: {{name}}
        image: {{user}}/{{project}}:{{image}}
        workingDir: /root
        imagePullPolicy: Always
        command: ["/bin/bash"]
        args: ["-c", ">- cp -r /{{pvc}}/.ssh /root && git clone git@github.com:{{user}}/{{project}}.git && cd {{project}} && wandb login {{wandb_key}} && ls && {{cmd}}"]
        resources:
          requests:
            cpu: "{{cpu}}"
            memory: {{mem}}Gi
            nvidia.com/gpu: "{{gpu}}"
          limits:
            cpu: "{{cpu}}"
            memory: {{mem}}Gi
            nvidia.com/gpu: "{{gpu}}"
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          - mountPath: /{{pvc}}
            name: {{pvc}}
      restartPolicy: Never
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: {{pvc}}
          persistentVolumeClaim:
            claimName: {{pvc}}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nautilus.io/group
                    operator: {{haosu}}
                    values:
                      - haosu
                  - key: nvidia.com/gpu.product
                    operator: In
                    values:
                      - NVIDIA-A10
  backoffLimit: 5
